<?php

require_once __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\User;
use App\Models\EmployerDocument;
use Illuminate\Support\Facades\DB;

echo "=== EMPLOYER JOB POSTING FIX ===\n\n";

// Get all employers who cannot post jobs
$employers = User::where('role', 'employer')->get()->filter(function($employer) {
    return !$employer->canPostJobs();
});

if ($employers->isEmpty()) {
    echo "✅ All employers can already post jobs! No fixes needed.\n";
    exit;
}

echo "Found " . $employers->count() . " employer(s) who cannot post jobs.\n\n";

echo "Choose what to fix:\n";
echo "1. Enable KYC verification for all employers\n";
echo "2. Create and approve required documents for all employers\n";
echo "3. Both KYC and documents (complete fix)\n";
echo "4. Fix specific employer by email\n";
echo "5. Show diagnostic only (no changes)\n\n";

echo "Enter your choice (1-5): ";
$handle = fopen("php://stdin", "r");
$choice = trim(fgets($handle));
fclose($handle);

switch ($choice) {
    case '1':
        fixKycForAllEmployers($employers);
        break;
    
    case '2':
        fixDocumentsForAllEmployers($employers);
        break;
        
    case '3':
        fixKycForAllEmployers($employers);
        fixDocumentsForAllEmployers($employers);
        break;
        
    case '4':
        fixSpecificEmployer();
        break;
        
    case '5':
        showDiagnosticOnly($employers);
        break;
        
    default:
        echo "Invalid choice. Exiting.\n";
        exit;
}

function fixKycForAllEmployers($employers) {
    echo "\n🔧 FIXING KYC STATUS...\n";
    
    foreach ($employers as $employer) {
        if (!$employer->isKycVerified()) {
            $employer->update([
                'kyc_status' => 'verified',
                'kyc_verified_at' => now(),
                'kyc_data' => [
                    'session_id' => 'admin-fix-' . time(),
                    'status' => 'completed',
                    'completed_at' => now()->toIso8601String(),
                    'admin_override' => true,
                    'note' => 'Fixed by admin for job posting access'
                ]
            ]);
            
            echo "   ✅ Fixed KYC for {$employer->name} ({$employer->email})\n";
        }
    }
}

function fixDocumentsForAllEmployers($employers) {
    echo "\n📋 FIXING REQUIRED DOCUMENTS...\n";
    
    $requiredTypes = collect(EmployerDocument::getDocumentTypes())
        ->filter(fn($config) => $config['required'])
        ->keys();
    
    foreach ($employers as $employer) {
        foreach ($requiredTypes as $type) {
            $config = EmployerDocument::getDocumentTypes()[$type];
            
            // Check if document already exists and is approved
            $existingDoc = $employer->employerDocuments()
                ->where('document_type', $type)
                ->where('status', 'approved')
                ->first();
                
            if (!$existingDoc) {
                // Check if document exists but not approved
                $pendingDoc = $employer->employerDocuments()
                    ->where('document_type', $type)
                    ->first();
                
                if ($pendingDoc) {
                    // Approve existing document
                    $pendingDoc->update([
                        'status' => 'approved',
                        'reviewed_at' => now(),
                        'reviewed_by' => 1, // Assume admin user ID 1
                        'admin_notes' => 'Auto-approved by admin fix script'
                    ]);
                    
                    echo "   ✅ Approved existing {$config['label']} for {$employer->name}\n";
                } else {
                    // Create dummy approved document
                    EmployerDocument::create([
                        'user_id' => $employer->id,
                        'document_type' => $type,
                        'document_name' => $config['label'] . ' - Admin Generated',
                        'file_path' => 'documents/admin-generated-' . $type . '.pdf',
                        'file_name' => 'admin-generated-' . $type . '.pdf',
                        'file_size' => 1024,
                        'mime_type' => 'application/pdf',
                        'status' => 'approved',
                        'submitted_at' => now(),
                        'reviewed_at' => now(),
                        'reviewed_by' => 1, // Assume admin user ID 1
                        'admin_notes' => 'Generated by admin fix script for testing purposes'
                    ]);
                    
                    echo "   ✅ Created and approved {$config['label']} for {$employer->name}\n";
                }
            }
        }
    }
}

function fixSpecificEmployer() {
    echo "\nEnter employer email: ";
    $handle = fopen("php://stdin", "r");
    $email = trim(fgets($handle));
    fclose($handle);
    
    $employer = User::where('role', 'employer')
                    ->where('email', $email)
                    ->first();
    
    if (!$employer) {
        echo "❌ Employer with email '{$email}' not found.\n";
        return;
    }
    
    echo "\nFound: {$employer->name} ({$employer->email})\n";
    echo "Current status: " . ($employer->canPostJobs() ? 'Can post jobs' : 'Cannot post jobs') . "\n\n";
    
    if ($employer->canPostJobs()) {
        echo "✅ This employer can already post jobs!\n";
        return;
    }
    
    echo "What to fix:\n";
    echo "1. KYC only\n";
    echo "2. Documents only\n";
    echo "3. Both\n\n";
    
    echo "Enter choice (1-3): ";
    $handle = fopen("php://stdin", "r");
    $choice = trim(fgets($handle));
    fclose($handle);
    
    $employers = collect([$employer]);
    
    switch ($choice) {
        case '1':
            fixKycForAllEmployers($employers);
            break;
        case '2':
            fixDocumentsForAllEmployers($employers);
            break;
        case '3':
            fixKycForAllEmployers($employers);
            fixDocumentsForAllEmployers($employers);
            break;
        default:
            echo "Invalid choice.\n";
            return;
    }
    
    // Refresh and check
    $employer->refresh();
    echo "\n" . ($employer->canPostJobs() ? "✅ Fixed! Employer can now post jobs." : "❌ Still cannot post jobs. Please check manually.") . "\n";
}

function showDiagnosticOnly($employers) {
    echo "\n📊 DIAGNOSTIC REPORT:\n\n";
    
    foreach ($employers as $employer) {
        echo "👤 {$employer->name} ({$employer->email}):\n";
        echo "   KYC Status: {$employer->kyc_status} - " . ($employer->isKycVerified() ? 'Verified' : 'NOT Verified') . "\n";
        
        $requiredTypes = collect(EmployerDocument::getDocumentTypes())
            ->filter(fn($config) => $config['required'])
            ->keys();
            
        $approvedCount = 0;
        foreach ($requiredTypes as $type) {
            $doc = $employer->employerDocuments()
                ->where('document_type', $type)
                ->where('status', 'approved')
                ->first();
            if ($doc) $approvedCount++;
        }
        
        echo "   Required Documents: {$approvedCount}/" . $requiredTypes->count() . " approved\n";
        echo "   Can Post Jobs: " . ($employer->canPostJobs() ? 'Yes' : 'No') . "\n\n";
    }
}

echo "\n=== FIX COMPLETE ===\n";
echo "Please test job posting functionality in the browser.\n";
echo "If issues persist, check:\n";
echo "1. Middleware registration in app/Http/Kernel.php\n";
echo "2. Route configuration in routes/web.php\n";
echo "3. User session and authentication\n";
